version: '3.8'

services:
  bref-php:
    platform: linux/x86_64
    container_name: bref-php
    build:
      context: ./
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./app:/var/app
    working_dir: /var/app
    tty: true
