service: app

provider:
    name: aws
    region: ap-northeast-1
    profile: default
    stage: dev
    iam:
      role:
        statements:
          - Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
            Resource: "arn:aws:s3:::bref-php-sample/*"

plugins:
  - ./vendor/bref/bref

functions:
    web:
        handler: index.php
        runtime: php-82
        timeout: 28
        events:
          - s3:
              bucket: bref-php-sample
              existing: true
              event: s3:ObjectCreated:*
              rules:
                - prefix: uploads/

package:
  patterns:
    - '!tests/**'
