service: app-${opt:stage, 'dev'}

provider:
  name: aws
  region: ap-northeast-1

plugins:
  - ./vendor/bref/bref

functions:
  s3-event:
    handler: index.php
    runtime: php-82

package:
  patterns:
    - '!tests/**'
