service: app

provider:
    name: aws
    region: ap-northeast-1
    profile: default
    stage: dev

plugins:
  - ./vendor/bref/bref

functions:
    web:
        handler: index.php
        runtime: php-82-fpm
        timeout: 28
        events:
          - s3:
              bucket: bref-php-sample
              existing: true
              event: s3:ObjectCreated:*

package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'
