service: app

provider:
    name: aws
    region: ap-northeast-1

plugins:
  - ./vendor/bref/bref

functions:
    web:
        handler: public/index.php
        runtime: php-82-fpm
        timeout: 28
        events:
            - httpApi: '*'

package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'
